language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to run Xvfb for tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
#install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests
